version: 2
jobs:
  test_and_lint:
    machine: true
    working_directory: ~/workspace
    steps:
      - checkout
      - run:
          name: Test and Lint
          command: |
            docker-compose -f docker-compose-circleci.yml up

  deploy:
    machine: true
    working_directory: ~/workspace
    steps:
      - checkout
      - deploy:
          name: Deploy to Heroku
          command: exit 0
          # command: |
          #   docker login -u _ -p $HEROKU_API_KEY registry.heroku.com
          #   curl https://cli-assets.heroku.com/install.sh | sh
          #   heroku container:push web -a $HEROKU_APP_NAME
          #   heroku container:release web -a $HEROKU_APP_NAME

workflows:
  version: 2
  test_lint_and_deploy:
    jobs:
      - test_and_lint
      - deploy:
          requires:
            - test_and_lint
          filters:
            branches:
              only: master
